In [1]:
import pandas as pd
import zipfile
import plotly.express as px
import matplotlib.pyplot as plt
import requests
from io import BytesIO
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from my_plots import *
import streamlit as st

In [10]:
file = 'combined_data.csv'
with open(file) as f:
    data =pd.read_csv(f)
    data = data.drop(columns=["Unnamed: 0"])
data.head()

,1. open,2. high,3. low,4. close,5. volume,symbol,price_date,reportedEPS,estimatedEPS,surprise,surprisePercentage,earnings_release_date
0,17.67,17.890,17.5100,17.76,2374099,WEN,2024-10-07,0.25,0.25,0.0,0.0,2024-09-30
1,17.40,17.750,17.3600,17.63,2498220,WEN,2024-10-04,0.25,0.25,0.0,0.0,2024-09-30
2,17.31,17.425,17.2637,17.29,1829568,WEN,2024-10-03,0.25,0.25,0.0,0.0,2024-09-30
3,17.50,17.645,17.3700,17.38,3397164,WEN,2024-10-02,0.25,0.25,0.0,0.0,2024-09-30
4,17.64,17.800,17.4700,17.66,2279654,WEN,2024-10-01,0.25,0.25,0.0,0.0,2024-09-30